/** Curated memorable words for three-reel session codes. */
export const WORD_LIST: readonly string[] = [
  "apple",
  "aurora",
  "bamboo",
  "beacon",
  "blizzard",
  "breeze",
  "canyon",
  "cascade",
  "cedar",
  "cipher",
  "cobalt",
  "comet",
  "copper",
  "coral",
  "cosmos",
  "crimson",
  "crystal",
  "delta",
  "ember",
  "falcon",
  "fern",
  "fjord",
  "flint",
  "forest",
  "frost",
  "galaxy",
  "glacier",
  "graphite",
  "harbor",
  "hazel",
  "helix",
  "horizon",
  "hydrogen",
  "indigo",
  "ivory",
  "jade",
  "jupiter",
  "karma",
  "kite",
  "lagoon",
  "lattice",
  "lemon",
  "lotus",
  "lumen",
  "maple",
  "marble",
  "meadow",
  "mercury",
  "meteor",
  "mimosa",
  "mirror",
  "monarch",
  "nebula",
  "nectar",
  "nickel",
  "night",
  "nova",
  "oak",
  "obsidian",
  "ocean",
  "olive",
  "onyx",
  "opal",
  "orbit",
  "orchid",
  "oxygen",
  "pebble",
  "phoenix",
  "pine",
  "plasma",
  "plume",
  "prism",
  "pulse",
  "quartz",
  "quasar",
  "quiet",
  "radar",
  "raven",
  "reef",
  "ripple",
  "river",
  "rocket",
  "sable",
  "sage",
  "sapphire",
  "scarlet",
  "shadow",
  "signal",
  "silver",
  "slate",
  "solar",
  "spark",
  "spruce",
  "stone",
  "storm",
  "summit",
  "surge",
  "swift",
  "talon",
  "tempo",
  "terra",
  "thistle",
  "thunder",
  "tide",
  "timber",
  "titan",
  "topaz",
  "torch",
  "torrent",
  "tulip",
  "tundra",
  "ultra",
  "umbra",
  "valley",
  "vapor",
  "velvet",
  "vertex",
  "violet",
  "vista",
  "volt",
  "vortex",
  "walnut",
  "wave",
  "willow",
  "wind",
  "winter",
  "wolf",
  "wonder",
  "xenon",
  "yellow",
  "zenith",
  "zinc",
  "anchor",
  "arrow",
  "atlas",
  "badge",
  "basin",
  "bison",
  "blade",
  "bloom",
  "bolt",
  "bridge",
  "bronze",
  "cabin",
  "cactus",
  "camel",
  "candle",
  "cargo",
  "castle",
  "chalk",
  "charm",
  "cherry",
  "chief",
  "chord",
  "citrus",
  "cliff",
  "cloud",
  "clover",
  "coach",
  "cobra",
  "cocoa",
  "coffee",
  "compass",
  "crane",
  "creek",
  "crown",
  "cube",
  "daisy",
  "dawn",
  "desert",
  "diamond",
  "dragon",
  "dream",
  "drift",
  "eagle",
  "echo",
  "elm",
  "emerald",
  "engine",
  "fable",
  "feather",
  "field",
  "flame",
  "flute",
  "forge",
  "fox",
  "garden",
  "garnet",
  "ghost",
  "ginger",
  "glass",
  "gold",
  "grape",
  "grove",
  "guard",
  "hawk",
  "honey",
  "hound",
  "iris",
  "island",
  "jewel",
  "jungle",
  "key",
  "knight",
  "lake",
  "lance",
  "lava",
  "leaf",
  "legend",
  "lion",
  "magic",
  "mango",
  "mesa",
  "mint",
  "mist",
  "moon",
  "moss",
  "mountain",
  "mushroom",
  "navy",
  "nest",
  "north",
  "oasis",
  "omega",
  "orange",
  "otter",
  "owl",
  "panda",
  "paper",
  "pearl",
  "pepper",
  "petal",
  "pilot",
  "pixel",
  "planet",
  "pluto",
  "polar",
  "pond",
  "portal",
  "queen",
  "quest",
  "rain",
  "ridge",
  "robin",
  "rose",
  "ruby",
  "sand",
  "saturn",
  "seed",
  "shell",
  "shield",
  "smoke",
  "snow",
  "south",
  "spider",
  "star",
  "steel",
  "sugar",
  "sun",
  "swan",
  "table",
  "tiger",
  "tower",
  "tree",
  "trumpet",
  "turtle",
  "whale",
  "wheat",
  "wing",
  "wood",
  "yarn",
  "zebra",
  "fantastic",
];

const WORD_SET = new Set(WORD_LIST);

export function isValidWord(word: string): boolean {
  return WORD_SET.has(word.toLowerCase().trim());
}

export function normalizeWord(word: string): string {
  return word.toLowerCase().trim();
}

export function pickRandomWord(exclude?: string): string {
  const len = WORD_LIST.length;
  if (len === 0) return "apple";
  let word = WORD_LIST[Math.floor(Math.random() * len)] ?? "apple";
  if (exclude && len > 1) {
    let guard = 0;
    while (word === exclude && guard < 20) {
      word = WORD_LIST[Math.floor(Math.random() * len)] ?? "apple";
      guard++;
    }
  }
  return word;
}

export function wordsToSlug(words: [string, string, string]): string {
  return words.map(normalizeWord).join("-");
}

export function parseSessionSlug(slug: string): [string, string, string] | null {
  const parts = slug.toLowerCase().trim().split("-").filter(Boolean);
  if (parts.length !== 3) return null;
  const [a, b, c] = parts;
  if (!a || !b || !c) return null;
  if (!isValidWord(a) || !isValidWord(b) || !isValidWord(c)) return null;
  return [a, b, c];
}

export function formatSessionLabel(words: [string, string, string]): string {
  return words.map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" · ");
}

/** Stable SSR default — replaced client-side after mount. */
export const DEFAULT_WORDS: [string, string, string] = ["apple", "hydrogen", "fantastic"];
